[package]
name = "oxidebot_app"
version = "1.0.0"
edition = "2024"
rust-version = "1.97.1"
description = "Example OxideBot application for the OxideBot Root template"
publish = false

[dependencies]
anyhow = "1.0.104"
oxidebot = { git = "https://github.com/canxin121/oxidebot", rev = "4e1ba8bcdd24b8d3965809450847dbee2689f5ff", version = "1.0.0" }
oxidebot-adapter-telegram = { git = "https://github.com/canxin121/oxidebot", rev = "4e1ba8bcdd24b8d3965809450847dbee2689f5ff", version = "1.0.0" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.23"

[profile.release]
lto = true
strip = true
opt-level = "z"   # Optimize for size.
codegen-units = 1
panic = "abort"
