[package]
name = "my_oxidebot"
version = "0.2.0"
edition = "2024"
rust-version = "1.97"
description = "OxideBot runtime bundled by OxideBot for Root"
repository = "https://github.com/canxin121/oxidebot_root"
publish = false

[dependencies]
onebot_v11_oxidebot = "0.1.4"
telegram_bot_oxidebot = "0.1.4"
oxidebot = "0.1.8"
tokio = { version = "1.53.1", features = ["full"] }
tracing-subscriber = "0.3.23"
anyhow = "1.0.104"
china_unicom_oxidebot = { version = "0.3.0", git = "https://github.com/canxin121/china_unicom_oxidebot" }

[profile.release]
lto = true
strip = true
opt-level = "z"   # Optimize for size.
codegen-units = 1
panic = "abort"
